#!/bin/bash
set -e
BRANCH=$( git branch | grep \* | cut -d ' ' -f2 )

sed "s#octavia.git.*#octavia.git ${BRANCH}#g" -i ./elements/amphora-agent/source-repository-amphora-agent
git add ./elements/amphora-agent/source-repository-amphora-agent
